AWSTemplateFormatVersion: "2010-09-09"

Description: AWS S3 Bucket creation

# Add your code here!

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256